import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans, Manrope} from "next/font/google";

export const metadata: Metadata = {
  title: "CNN Visualiser",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});
const worksans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-worksans",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${worksans.variable}`}>
      <body className="p-4 font-main">{children}</body>
    </html>
  );
}
